### ISSUE TITLE
nfs rwx folder has 000 as permission  

### ISSUE THREAD

**Issue by mbu147** [openebs-archive/dynamic-nfs-provisioner#124]
**Describe the bug:**
I created many RWX nfs shares with nfs-provisioner. As backend storageclass i use openebs-jiva.
Sometimes every nfs share mount get the permission 000
Then, the mount folder looks like
```
root@nfs-pvc-3da88edc-2b97-4165-93ba-49bc54056cc6-fb8f5fd66-jfz6b:/ # ls -la
d---------   17 xfs      xfs           4096 Oct 29 14:15 nfsshare
```
in the nfs-pvc pod.
Cause of that, the nginx container where the nfs-pvc is mounted also have 000 on the folder and cannot read the files within

The files in the mount folder have the correct permissions.

**Expected behaviour:**
Default mount permission 755 or something similar

**Steps to reproduce the bug:**
Just create a new nfs rwx pvc and wait. After some time the running nginx container cannot read the folder anymore.

**The output of the following commands will help us better understand what's going on**:
* `kubectl get pods -n <openebs_namespace> --show-labels`
https://pastebin.com/wxBrUzGy
* `kubectl get pvc -n <openebs_namespace>`
https://pastebin.com/H4MuJs2j
* `kubectl get pvc -n <application_namespace>`
https://pastebin.com/fnZinyN3

**Anything else we need to know?:**
jiva and nfs installed via helm charts
https://github.com/openebs/jiva-operator/tree/develop/deploy/helm/charts
https://github.com/openebs/dynamic-nfs-provisioner/tree/develop/deploy/helm/charts
helm config:
```
nfs-provisioner:
    rbac:
        pspEnabled: false
    podSecurityContext:
        fsGroup: 120
```
storage class:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-rwx
  annotations:
    openebs.io/cas-type: nfsrwx
    cas.openebs.io/config: |
      - name: NFSServerType
        value: "kernel"
      - name: BackendStorageClass
        value: "openebs-jiva-csi-default"
      #  LeaseTime defines the renewal period(in seconds) for client state
      - name: LeaseTime
      value: 30
      #  GraceTime defines the recovery period(in seconds) to reclaim locks
      - name: GraceTime
        value: 30
      #  FSGID defines the group permissions of NFS Volume. If it is set
      #  then non-root applications should add FSGID value under pod
      #  Supplemental groups
      - name: FSGID
        value: "120"
      - name: NFSServerResourceRequests
        value: |-
          cpu: 50m
          memory: 50Mi
      - name: NFSServerResourceLimits
        value: |-
          cpu: 100m
          memory: 100Mi
provisioner: openebs.io/nfsrwx
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
```

**Environment details:**
- OpenEBS version (use `kubectl get po -n openebs --show-labels`):
```
openebs/jiva-operator:3.0.0
openebs/provisioner-nfs:0.7.1
```
- Kubernetes version (use `kubectl version`):
`v1.21.5+k3s`
- Cloud provider or hardware configuration:
contabo vps hardware
- OS (e.g: `cat /etc/os-release`):
`AlmaLinux 8.4 (Electric Cheetah)`
- kernel (e.g: `uname -a`):
`4.18.0-305.19.1.el8_4.x86_64`

Do i have a misconfigured setup or is this a bug? 

Thanks for help!
