### ISSUE TITLE
nfs pvc seems to have damaged filesystem after restarting pod it's used by

### ISSUE THREAD

**Issue by edwmurph** [openebs-archive/dynamic-nfs-provisioner#133]
**Describe the bug:** A clear and concise description of what the bug is.

ReadWriteMany nfs pvc `pvc-55940b24-bd9a-4d63-911c-809f9bfc10cd` seems to have damaged filesystem after restarting pod it's used by

**Expected behaviour:** A concise description of what you expected to happen

**Steps to reproduce the bug:**

<details>
<summary>installed cstor via helm</summary>

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cstor
  namespace: openebs
spec:
  interval: 10m
  chart:
    spec:
      chart: cstor
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: openebs-cstor
        namespace: flux-system
  values:
    csiNode:
      kubeletDir: "/var/snap/microk8s/common/var/lib/kubelet/"
    openebs-ndm:
      # ndm options:
      # https://github.com/openebs/node-disk-manager/blob/develop/deploy/helm/charts/values.yaml#L44
      ndm:
        filters:
          osDiskExcludePaths: "/,/etc/hosts,/boot,/boot/firmware"
      featureGates:
        UseOSDisk:
          enabled: true
```
</details>

<details>
<summary>installed dynamic-nfs-provisioner via helm</summary>

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-nfs
  namespace: openebs
spec:
  interval: 10m
  timeout: 7m
  chart:
    spec:
      chart: nfs-provisioner
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: openebs-nfs
        namespace: flux-system
  values:
    nfsStorageClass:
      name: openebs-nfs
      backendStorageClass: cstor-csi
      isDefaultClass: true
      reclaimPolicy: Delete
    analytics:
      enabled: false
```
</details>

<details>
<summary>create PVCs</summary>

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
  labels:
    app: plex
spec:
  storageClassName: openebs-nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: media
  labels:
    app: plex
spec:
  storageClassName: openebs-nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

```
</details>

<details>
<summary>deploy plex</summary>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: plex
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      restartPolicy: Always
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: plex-data
          persistentVolumeClaim:
            claimName: plex-data
      containers:
        - name: plex
          image: ghcr.io/linuxserver/plex
          imagePullPolicy: Always
          env:
            - name: PLEX_CLAIM
              value: <redacted>
            - name: PGID
              value: '0'
            - name: PUID
              value: '0'
            - name: VERSION
              value: docker
            - name: TZ
              value: America/New_York
          ports:
            - containerPort: 32400
              name: pms-web
              protocol: TCP
            - containerPort: 32469
              name: dlna-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 3005
              name: plex-companion
              protocol: TCP
            - containerPort: 5353
              name: discovery-udp
              protocol: UDP
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: plex-config
            - mountPath: /data
              name: plex-data
```
</details>

then:
- initial plex pod starts up fine and is able to read/write to mounted `/config` dir 
- delete + recreate plex pod and then plex fails to start correctly + ssh'ing into container also reports unable to read `/config` directory

**The output of the following commands will help us better understand what's going on**:

<details>
<summary><code>kc get pods -n openebs --show-labels</code></summary>

```
NAME                                                              READY   STATUS    RESTARTS        AGE     LABELS
cstor-csi-node-vtf87                                              2/2     Running   9 (4d8h ago)    10d     chart=cstor-3.1.0,component=openebs-cstor-csi-node,controller-revision-hash=6d59fbb8f8,heritage=Helm,name=openebs-cstor-csi-node,openebs.io/component-name=openebs-cstor-csi-node,openebs.io/version=3.1.0,pod-template-generation=1,release=cstor
cstor-cvc-operator-6f57946444-m5dmq                               1/1     Running   1 (4d8h ago)    9d      chart=cstor-3.1.0,component=cvc-operator,heritage=Helm,name=cvc-operator,openebs.io/component-name=cvc-operator,openebs.io/version=3.1.0,pod-template-hash=6f57946444,release=cstor
cstor-openebs-ndm-operator-55b6c8846b-njqvc                       1/1     Running   4 (4d8h ago)    10d     app=openebs-ndm-operator,chart=openebs-ndm-1.8.0,component=openebs-ndm-operator,heritage=Helm,name=openebs-ndm-operator,openebs.io/component-name=openebs-ndm-operator,openebs.io/version=1.8.0,pod-template-hash=55b6c8846b,release=cstor
cstor-openebs-ndm-rcgks                                           1/1     Running   6 (4d8h ago)    10d     app=openebs-ndm,chart=openebs-ndm-1.8.0,component=ndm,controller-revision-hash=8c8486ccd,heritage=Helm,name=openebs-ndm,openebs.io/component-name=ndm,openebs.io/version=1.8.0,pod-template-generation=1,release=cstor
cstor-storage-jlsq-c57dd5d9b-56c5p                                3/3     Running   0               4d8h    app=cstor-pool,openebs.io/cstor-pool-cluster=cstor-storage,openebs.io/cstor-pool-instance=cstor-storage-jlsq,openebs.io/version=3.1.0,pod-template-hash=c57dd5d9b
nfs-pvc-9b5e65a0-535e-48b6-8d8b-8dec93a32ec4-5db44b59c4-bdj5v     1/1     Running   0               3h48m   openebs.io/nfs-server=nfs-pvc-9b5e65a0-535e-48b6-8d8b-8dec93a32ec4,pod-template-hash=5db44b59c4
cstor-csi-controller-0                                            6/6     Running   39 (161m ago)   10d     chart=cstor-3.1.0,component=openebs-cstor-csi-controller,controller-revision-hash=cstor-csi-controller-867c797bd7,heritage=Helm,name=openebs-cstor-csi-controller,openebs.io/component-name=openebs-cstor-csi-controller,openebs.io/version=3.1.0,release=cstor,statefulset.kubernetes.io/pod-name=cstor-csi-controller-0
cstor-csi-node-2pvs2                                              2/2     Running   4 (9d ago)      10d     chart=cstor-3.1.0,component=openebs-cstor-csi-node,controller-revision-hash=6d59fbb8f8,heritage=Helm,name=openebs-cstor-csi-node,openebs.io/component-name=openebs-cstor-csi-node,openebs.io/version=3.1.0,pod-template-generation=1,release=cstor
cstor-storage-gv6b-5d48f7854d-hpkp4                               3/3     Running   1 (3d21h ago)   4d8h    app=cstor-pool,openebs.io/cstor-pool-cluster=cstor-storage,openebs.io/cstor-pool-instance=cstor-storage-gv6b,openebs.io/version=3.1.0,pod-template-hash=5d48f7854d
cstor-cspc-operator-cf87fdc89-zpnll                               1/1     Running   2 (9d ago)      10d     chart=cstor-3.1.0,component=cspc-operator,heritage=Helm,name=cspc-operator,openebs.io/component-name=cspc-operator,openebs.io/version=3.1.0,pod-template-hash=cf87fdc89,release=cstor
cstor-admission-server-77c48bb8c-xvxzw                            1/1     Running   0               9d      app=cstor-admission-webhook,chart=cstor-3.1.0,component=cstor-admission-webhook,heritage=Helm,openebs.io/component-name=cstor-admission-webhook,openebs.io/version=3.1.0,pod-template-hash=77c48bb8c,release=cstor
cstor-openebs-ndm-pbb6b                                           1/1     Running   2 (9d ago)      10d     app=openebs-ndm,chart=openebs-ndm-1.8.0,component=ndm,controller-revision-hash=8c8486ccd,heritage=Helm,name=openebs-ndm,openebs.io/component-name=ndm,openebs.io/version=1.8.0,pod-template-generation=1,release=cstor
openebs-nfs-nfs-provisioner-7884cc9556-4kdds                      1/1     Running   4 (150m ago)    3h48m   app=nfs-provisioner,chart=nfs-provisioner-0.9.0,component=nfs-provisioner,heritage=Helm,name=openebs-nfs-provisioner,openebs.io/component-name=openebs-nfs-provisioner,openebs.io/version=0.9.0,pod-template-hash=7884cc9556,release=openebs-nfs
cstor-storage-8cqv-ffbcbb6c7-78shd                                3/3     Running   0               3h48m   app=cstor-pool,openebs.io/cstor-pool-cluster=cstor-storage,openebs.io/cstor-pool-instance=cstor-storage-8cqv,openebs.io/version=3.1.0,pod-template-hash=ffbcbb6c7
cstor-openebs-ndm-rfgbz                                           1/1     Running   5 (4d8h ago)    10d     app=openebs-ndm,chart=openebs-ndm-1.8.0,component=ndm,controller-revision-hash=8c8486ccd,heritage=Helm,name=openebs-ndm,openebs.io/component-name=ndm,openebs.io/version=1.8.0,pod-template-generation=1,release=cstor
cstor-csi-node-w5hq7                                              2/2     Running   10 (4d8h ago)   10d     chart=cstor-3.1.0,component=openebs-cstor-csi-node,controller-revision-hash=6d59fbb8f8,heritage=Helm,name=openebs-cstor-csi-node,openebs.io/component-name=openebs-cstor-csi-node,openebs.io/version=3.1.0,pod-template-generation=1,release=cstor
nfs-pvc-d7e6f64d-68d6-412b-98c0-f0a294508794-5ddb76577d-8szp9     1/1     Running   0               162m    openebs.io/nfs-server=nfs-pvc-d7e6f64d-68d6-412b-98c0-f0a294508794,pod-template-hash=5ddb76577d
nfs-pvc-55940b24-bd9a-4d63-911c-809f9bfc10cd-587c7fdccd-r5gkx     1/1     Running   0               162m    openebs.io/nfs-server=nfs-pvc-55940b24-bd9a-4d63-911c-809f9bfc10cd,pod-template-hash=587c7fdccd
pvc-f2997e87-c209-4200-baa7-3a520c2211e1-target-b5bb994c9-x5vzq   3/3     Running   0               149m    app=cstor-volume-manager,monitoring=volume_exporter_prometheus,openebs.io/persistent-volume-claim=nfs-pvc-d7e6f64d-68d6-412b-98c0-f0a294508794,openebs.io/persistent-volume=pvc-f2997e87-c209-4200-baa7-3a520c2211e1,openebs.io/target=cstor-target,openebs.io/version=3.1.0,pod-template-hash=b5bb994c9
pvc-24b04637-8621-48d9-beca-211b15ccc675-target-7b58f96b5ffkvrw   3/3     Running   0               149m    app=cstor-volume-manager,monitoring=volume_exporter_prometheus,openebs.io/persistent-volume-claim=nfs-pvc-9b5e65a0-535e-48b6-8d8b-8dec93a32ec4,openebs.io/persistent-volume=pvc-24b04637-8621-48d9-beca-211b15ccc675,openebs.io/target=cstor-target,openebs.io/version=3.1.0,pod-template-hash=7b58f96b5f
pvc-4a009034-ff10-453a-a3f7-049b8a219ff0-target-58cb6d448dmg2pm   3/3     Running   0               149m    app=cstor-volume-manager,monitoring=volume_exporter_prometheus,openebs.io/persistent-volume-claim=nfs-pvc-55940b24-bd9a-4d63-911c-809f9bfc10cd,openebs.io/persistent-volume=pvc-4a009034-ff10-453a-a3f7-049b8a219ff0,openebs.io/target=cstor-target,openebs.io/version=3.1.0,pod-template-hash=58cb6d448d
```
</details>

<details>
<summary><code>kubectl get pvc -n openebs</code></summary>

```
NAME                                           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nfs-pvc-9b5e65a0-535e-48b6-8d8b-8dec93a32ec4   Bound    pvc-24b04637-8621-48d9-beca-211b15ccc675   500Mi      RWO            cstor-csi      24h
nfs-pvc-d7e6f64d-68d6-412b-98c0-f0a294508794   Bound    pvc-f2997e87-c209-4200-baa7-3a520c2211e1   500Gi      RWO            cstor-csi      163m
nfs-pvc-55940b24-bd9a-4d63-911c-809f9bfc10cd   Bound    pvc-4a009034-ff10-453a-a3f7-049b8a219ff0   1Gi        RWO            cstor-csi      163m
```
</details>

<details>
<summary><code>kubectl describe pvc -n media</code></summary>

```
479s 3:48:34 ~/code/personal/personal⟩ kc describe pvc -n media                                                ± master
Name:          plex-data
Namespace:     media
StorageClass:  openebs-nfs
Status:        Bound
Volume:        pvc-d7e6f64d-68d6-412b-98c0-f0a294508794
Labels:        app=plex
               kustomize.toolkit.fluxcd.io/name=media
               kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: openebs.io/nfsrwx
               volume.kubernetes.io/storage-provisioner: openebs.io/nfsrwx
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      500Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       plex-85556c488b-8s9lv
Events:        <none>


Name:          plex-config
Namespace:     media
StorageClass:  openebs-nfs
Status:        Bound
Volume:        pvc-55940b24-bd9a-4d63-911c-809f9bfc10cd
Labels:        app=plex
               kustomize.toolkit.fluxcd.io/name=media
               kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: openebs.io/nfsrwx
               volume.kubernetes.io/storage-provisioner: openebs.io/nfsrwx
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       plex-85556c488b-8s9lv
Events:        <none>
```
</details>

<details>
<summary><code>root@plex-85556c488b-8s9lv:/# ls -l /config</code></summary>

```
ls: reading directory '/config': Input/output error
total 0
```
</details>

<details>
<summary><code>kubectl logs -n media plex-85556c488b-8s9lv</code></summary>

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing...
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

chown: changing ownership of '/config': Read-only file system
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing...
chown: changing ownership of '/config': Read-only file system
chown: cannot access '/config/*': Input/output error
[cont-init.d] 40-chown-files: exited 1.
[cont-init.d] 45-plex-claim: executing...
Temporarily starting Plex Media Server.
Waiting for Plex to generate its config
Waiting for database creation to complete...
md5sum: '/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db-wal': Input/output error
PMS: failure detected. Read/write access is required for path: /config/Library/Application Support/Plex Media Server
Waiting for database creation to complete...
md5sum: '/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db-wal': Input/output error
```
</details>

**Anything else we need to know?:**

any insights would be greatly appreciated this is blocking my personal on prem plex media server journey!

**Environment details:**

on prem cluster:
- 3 raspberry pi 4 4gb mem node microk8s cluster
- 3 500gb samsung 870 evo disks

<details>
<summary><code>kubectl version</code></summary>

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:17:57Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.3-2+0d2db09fa6fbbb", GitCommit:"0d2db09fa6fbbbf8e7fd3e4c9d9e1c4b29f66481", GitTreeState:"clean", BuildDate:"2022-01-26T22:17:11Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/arm64"}
```
</details>

<details>
<summary><code>cat /etc/os-release</code> in container</summary>

```
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
</details>

<details>
<summary><code>uname -a</code></summary>

```
Linux plex-5cd676cb7d-jsjk2 5.4.0-1052-raspi #58-Ubuntu SMP PREEMPT Mon Feb 7 16:52:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```
</details>
