### ISSUE TITLE
Add support for backend cloned PVC

### ISSUE THREAD

**Issue by tingjiec** [openebs-archive/dynamic-nfs-provisioner#134]
**Describe the problem/challenge you have**
There is a requirement that want to provision nfs PV by clone an original backend PVC (the backend PVC CSI should support snapshot/clone, for example, LocalPV lvm or cStor).

**Describe the solution you'd like**
In the StorageClass yaml file, add dataSource annotation, then provisioner create backend PVC by clone original PVC by dataSource.
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-rwx
  annotations:
    openebs.io/cas-type: nfsrwx
    cas.openebs.io/config: |
      - name: NFSServerType
        value: "kernel"
      - name: BackendStorageClass
        value: "openebs-hostpath"
      - name: dataSource
        value: "backend-origin-pvc"
```

**Anything else you would like to add:**
If we can directly add the snapshot/clone support for nfs PVC, that is fine also.

**Environment:**
- OpenEBS version (use `kubectl get po -n openebs --show-labels`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- kernel (e.g: `uname -a`):
- others:

**Vote on this issue!**

This is an invitation to the OpenEBS community to vote on issues.  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"
