### ISSUE TITLE
Would it be possible to use nfs-provisioner with openebs-jiva to get HA replication?

### ISSUE THREAD

**Issue by keskival** [openebs-archive/dynamic-nfs-provisioner#152]
**Describe the problem/challenge you have**
I need high-availability replication support which would otherwise be provided by Jiva, but it doesn't support `ReadWriteMany`.

I tried to make Jiva use replica storage class of openebs-rwx but that doesn't work because of the aforementioned limitation.

**Describe the solution you'd like**
Perhaps it would work the other way around, putting replicated Jiva storage class to back the NFS provisioner? It would be nice to have some documentation about this use case.

Edit: Actually I tried it the other way around now, NFS provisioner using a replicated OpenEBS Jiva replication to back it, and it works perfectly!

Some more information about my set up here: 
https://www.costacoders.es/news/2022-12-24_kubernetes/

**Vote on this issue!**

This is an invitation to the OpenEBS community to vote on issues.  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "The project would be better with this feature added"
- :-1: for "This feature will not enhance the project in a meaningful way"

**Comment by keskival** [comment]
I got this working with something like this:
```
apiVersion: openebs.io/v1alpha1
kind: JivaVolumePolicy
metadata:
  name: openebs-jiva-default-policy
  namespace: openebs
spec:
  replicaSC: openebs-hostpath
  target:
    replicationFactor: 3
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-jiva-csi-default
parameters:
  cas-type: jiva
  policy: openebs-jiva-default-policy
provisioner: jiva.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: NFSServerType
        value: "kernel"
      - name: BackendStorageClass
        value: "openebs-jiva-csi-default"
    openebs.io/cas-type: nfsrwx
  name: openebs-rwx
provisioner: openebs.io/nfsrwx
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/basepath"
    openebs.io/cas-type: local
    storageclass.kubernetes.io/is-default-class: "true"
  name: openebs-hostpath
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
