### ISSUE TITLE
Optimize the time taken to recover from nfs pod (or its node) failure

### ISSUE THREAD

**Issue by kmova** [openebs-archive/dynamic-nfs-provisioner#36]
When the nfs pod went down, the recovery time for NFS to be active depends on the timeout of the K8s to determine that it is down and reschedule taking ~2 minutes. 

One option is to reduce by using custom tolerations like below:
```
          tolerations:
          - effect: NoExecute
            key: node.alpha.kubernetes.io/notReady
            operator: Exists
            tolerationSeconds: 0
          - effect: NoExecute
            key: node.alpha.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 0
          - effect: NoExecute
            key: node.kubernetes.io/not-ready
            operator: Exists
            tolerationSeconds: 0
          - effect: NoExecute
            key: node.kubernetes.io/unreachable
            operator: Exists
            tolerationSeconds: 0
```

Also, check for pod termination or restart strategies to make it faster.
